# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4000d192d7fef5394924a295c9ff6c581c30095e034c33255494d64b716547a907b2319ff14d78d5f7f4fb6b8095289d385a55a0e7f8891683c3481333d05c7

test:
  secret_key_base: 88543dc415289c5feb8591e6708d44489e9717fe05e21019f6a3e2ee3d8c27388493d9821e2d71dc4e162fbf3fd2291faaee1008e1fde407384755f0ab7a9af5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
